2024-07-18 10:28:57 | INFO | controller | 正在启动服务：
2024-07-18 10:28:57 | INFO | controller | 如需查看 服务日志 日志，请前往 /home/00_rag/fufan-chat-api/logs
2024-07-18 10:29:07 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1574557[0m]
2024-07-18 10:29:07 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 10:29:07 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 10:29:07 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:20001[0m (Press CTRL+C to quit)
2024-07-18 10:29:19 | INFO | controller | Register a new worker: http://192.168.110.131:21001
2024-07-18 10:29:19 | INFO | controller | Register done: http://192.168.110.131:21001, {'model_names': ['zhipu-api'], 'speed': 1, 'queue_length': 0}
2024-07-18 10:29:19 | INFO | stdout | [32mINFO[0m:     192.168.110.131:44052 - "[1mPOST /register_worker HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:29:19 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1574801[0m]
2024-07-18 10:29:19 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 10:29:19 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 10:29:19 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:20000[0m (Press CTRL+C to quit)
2024-07-18 10:29:20 | ERROR | stderr | Loading checkpoint shards:   0%|                                                                                                                                                                                                                                                          | 0/7 [00:00<?, ?it/s]
2024-07-18 10:29:20 | ERROR | stderr | Loading checkpoint shards:  14%|██████████████████████████████████▌                                                                                                                                                                                                               | 1/7 [00:00<00:03,  1.86it/s]
2024-07-18 10:29:21 | ERROR | stderr | Loading checkpoint shards:  29%|█████████████████████████████████████████████████████████████████████▏                                                                                                                                                                            | 2/7 [00:01<00:02,  1.83it/s]
2024-07-18 10:29:21 | ERROR | stderr | Loading checkpoint shards:  43%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                          | 3/7 [00:01<00:02,  1.92it/s]
2024-07-18 10:29:22 | ERROR | stderr | Loading checkpoint shards:  57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                       | 4/7 [00:02<00:01,  2.02it/s]
2024-07-18 10:29:22 | ERROR | stderr | Loading checkpoint shards:  71%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                     | 5/7 [00:02<00:00,  2.06it/s]
2024-07-18 10:29:23 | ERROR | stderr | Loading checkpoint shards:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 6/7 [00:02<00:00,  2.09it/s]
2024-07-18 10:29:23 | ERROR | stderr | Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.24it/s]
2024-07-18 10:29:23 | ERROR | stderr | Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.09it/s]
2024-07-18 10:29:23 | ERROR | stderr | 
2024-07-18 10:29:30 | INFO | controller | Register a new worker: http://192.168.110.131:20002
2024-07-18 10:29:30 | INFO | controller | Register done: http://192.168.110.131:20002, {'model_names': ['chatglm3-6b'], 'speed': 1, 'queue_length': 0}
2024-07-18 10:29:30 | INFO | stdout | [32mINFO[0m:     192.168.110.131:59030 - "[1mPOST /register_worker HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:29:30 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1574802[0m]
2024-07-18 10:29:30 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 10:29:30 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 10:29:30 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:20002[0m (Press CTRL+C to quit)
2024-07-18 10:29:41 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1575525[0m]
2024-07-18 10:29:41 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 10:29:41 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 10:29:41 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:8000[0m (Press CTRL+C to quit)
2024-07-18 10:30:04 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 10:30:04 | INFO | stdout | [32mINFO[0m:     192.168.110.131:41288 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:30:15 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 10:30:15 | INFO | stdout | [32mINFO[0m:     192.168.110.131:47268 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:30:49 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 10:30:49 | INFO | stdout | [32mINFO[0m:     192.168.110.131:35020 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:31:00 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 10:31:00 | INFO | stdout | [32mINFO[0m:     192.168.110.131:38724 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,550 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,551 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,553 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,554 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,555 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,555 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,558 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,562 INFO sqlalchemy.engine.Engine INSERT INTO conversation (id, user_id, name, chat_type, create_time) VALUES (%s, %s, %s, %s, %s)
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,562 INFO sqlalchemy.engine.Engine [generated in 0.00075s] ('b4b4e991-ac5d-4641-aaa6-e50d0e90ce24', 'ff4f9954-da8c-492f-965d-dc18224b1176', 'new_chat', 'real_time_search', datetime.datetime(2024, 7, 18, 10, 31, 10, 510265))
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,565 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,583 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,589 INFO sqlalchemy.engine.Engine SELECT conversation.id, conversation.user_id, conversation.name, conversation.chat_type, conversation.create_time
2024-07-18 10:31:10 | INFO | stdout | FROM conversation
2024-07-18 10:31:10 | INFO | stdout | WHERE conversation.id = %s
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,590 INFO sqlalchemy.engine.Engine [generated in 0.00108s] ('b4b4e991-ac5d-4641-aaa6-e50d0e90ce24',)
2024-07-18 10:31:10 | INFO | stdout | 2024-07-18 10:31:10,593 INFO sqlalchemy.engine.Engine ROLLBACK
2024-07-18 10:31:10 | INFO | stdout | [32mINFO[0m:     192.168.110.91:54745 - "[1mPOST /api/conversations HTTP/1.1[0m" [32m201 Created[0m
2024-07-18 10:31:34 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 10:31:34 | INFO | stdout | [32mINFO[0m:     192.168.110.131:56096 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:31:45 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 10:31:45 | INFO | stdout | [32mINFO[0m:     192.168.110.131:46796 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:32:19 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 10:32:19 | INFO | stdout | [32mINFO[0m:     192.168.110.131:54292 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:32:30 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 10:32:30 | INFO | stdout | [32mINFO[0m:     192.168.110.131:57226 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:33:04 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 10:33:04 | INFO | stdout | [32mINFO[0m:     192.168.110.131:45178 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:33:15 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 10:33:15 | INFO | stdout | [32mINFO[0m:     192.168.110.131:60748 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:33:49 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 10:33:49 | INFO | stdout | [32mINFO[0m:     192.168.110.131:36696 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:33:52 | INFO | stdout | [32mINFO[0m:     192.168.110.91:54814 - "[1mPOST /api/chat/search_engine_chat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:33:52 | INFO | stdout | 2024-07-18 10:33:52,182 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 10:33:52 | INFO | stdout | 2024-07-18 10:33:52,185 INFO sqlalchemy.engine.Engine SELECT conversation.id AS conversation_id, conversation.user_id AS conversation_user_id, conversation.name AS conversation_name, conversation.chat_type AS conversation_chat_type, conversation.create_time AS conversation_create_time
2024-07-18 10:33:52 | INFO | stdout | FROM conversation
2024-07-18 10:33:52 | INFO | stdout | WHERE conversation.id = %s
2024-07-18 10:33:52 | INFO | stdout | 2024-07-18 10:33:52,185 INFO sqlalchemy.engine.Engine [generated in 0.00104s] ('dd27db58-3002-43d9-be59-675a95ab07bb',)
2024-07-18 10:33:52 | INFO | stdout | 2024-07-18 10:33:52,188 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 10:33:52 | INFO | stdout | 2024-07-18 10:33:52,191 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 10:33:52 | INFO | stdout | 2024-07-18 10:33:52,194 INFO sqlalchemy.engine.Engine INSERT INTO message (id, conversation_id, chat_type, query, response, meta_data, feedback_score, feedback_reason, create_time) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, now())
2024-07-18 10:33:52 | INFO | stdout | 2024-07-18 10:33:52,194 INFO sqlalchemy.engine.Engine [generated in 0.00087s] ('1665f173-0672-4364-9ab7-2a80c61462fd', 'dd27db58-3002-43d9-be59-675a95ab07bb', 'real_time_search', ' 保罗乔治加盟了哪支NBA球队？', '', '{}', -1, '')
2024-07-18 10:33:52 | INFO | stdout | 2024-07-18 10:33:52,199 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 10:33:55 | INFO | stdout | 请求 URL 失败 https://zh.wikipedia.org/zh-hans/%E4%BF%9D%E7%BD%97%C2%B7%E4%B9%94%E6%B2%BB: Connection timeout to host https://zh.wikipedia.org/zh-hans/%E4%BF%9D%E7%BD%97%C2%B7%E4%B9%94%E6%B2%BB
2024-07-18 10:33:56 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2024-07-18 10:33:56 | ERROR | stderr | Traceback (most recent call last):
2024-07-18 10:33:56 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 284, in __call__
2024-07-18 10:33:56 | ERROR | stderr |     await wrap(partial(self.listen_for_disconnect, receive))
2024-07-18 10:33:56 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 273, in wrap
2024-07-18 10:33:56 | ERROR | stderr |     await func()
2024-07-18 10:33:56 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 223, in listen_for_disconnect
2024-07-18 10:33:56 | ERROR | stderr |     message = await receive()
2024-07-18 10:33:56 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
2024-07-18 10:33:56 | ERROR | stderr |     await self.message_event.wait()
2024-07-18 10:33:56 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/asyncio/locks.py", line 213, in wait
2024-07-18 10:33:56 | ERROR | stderr |     await fut
2024-07-18 10:33:56 | ERROR | stderr | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f6336f70b20
2024-07-18 10:33:56 | ERROR | stderr | 
2024-07-18 10:33:56 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-07-18 10:33:56 | ERROR | stderr | 
2024-07-18 10:33:56 | ERROR | stderr |   + Exception Group Traceback (most recent call last):
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-18 10:33:56 | ERROR | stderr |   |     result = await app(  # type: ignore[func-returns-value]
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-18 10:33:56 | ERROR | stderr |   |     return await self.app(scope, receive, send)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-18 10:33:56 | ERROR | stderr |   |     await super().__call__(scope, receive, send)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-07-18 10:33:56 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-18 10:33:56 | ERROR | stderr |   |     raise exc
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-18 10:33:56 | ERROR | stderr |   |     await self.app(scope, receive, _send)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-18 10:33:56 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-18 10:33:56 | ERROR | stderr |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-18 10:33:56 | ERROR | stderr |   |     raise exc
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-18 10:33:56 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
2024-07-18 10:33:56 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
2024-07-18 10:33:56 | ERROR | stderr |   |     await route.handle(scope, receive, send)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
2024-07-18 10:33:56 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
2024-07-18 10:33:56 | ERROR | stderr |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-18 10:33:56 | ERROR | stderr |   |     raise exc
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-18 10:33:56 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
2024-07-18 10:33:56 | ERROR | stderr |   |     await response(scope, receive, send)
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 270, in __call__
2024-07-18 10:33:56 | ERROR | stderr |   |     async with anyio.create_task_group() as task_group:
2024-07-18 10:33:56 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
2024-07-18 10:33:56 | ERROR | stderr |   |     raise BaseExceptionGroup(
2024-07-18 10:33:56 | ERROR | stderr |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-07-18 10:33:56 | ERROR | stderr |   +-+---------------- 1 ----------------
2024-07-18 10:33:56 | ERROR | stderr |     | Traceback (most recent call last):
2024-07-18 10:33:56 | ERROR | stderr |     |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 273, in wrap
2024-07-18 10:33:56 | ERROR | stderr |     |     await func()
2024-07-18 10:33:56 | ERROR | stderr |     |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 253, in stream_response
2024-07-18 10:33:56 | ERROR | stderr |     |     async for data in self.body_iterator:
2024-07-18 10:33:56 | ERROR | stderr |     |   File "/home/00_rag/fufan-chat-api/server/chat/search_engine_chat.py", line 92, in search_engine_chat_iterator
2024-07-18 10:33:56 | ERROR | stderr |     |     await milvusService.do_add_doc(docs=detail_results)
2024-07-18 10:33:56 | ERROR | stderr |     |   File "/home/00_rag/fufan-chat-api/server/knowledge_base/kb_service/milvus_kb_service.py", line 119, in do_add_doc
2024-07-18 10:33:56 | ERROR | stderr |     |     ids = self.milvus.add_documents(docs)
2024-07-18 10:33:56 | ERROR | stderr |     |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/langchain_core/vectorstores/base.py", line 485, in add_documents
2024-07-18 10:33:56 | ERROR | stderr |     |     return self.upsert(documents_, **kwargs)["succeeded"]
2024-07-18 10:33:56 | ERROR | stderr |     | TypeError: 'NoneType' object is not subscriptable
2024-07-18 10:33:56 | ERROR | stderr |     +------------------------------------
2024-07-18 10:34:00 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 10:34:00 | INFO | stdout | [32mINFO[0m:     192.168.110.131:36122 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:34:34 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 10:34:34 | INFO | stdout | [32mINFO[0m:     192.168.110.131:38712 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:34:45 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 10:34:45 | INFO | stdout | [32mINFO[0m:     192.168.110.131:40680 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:35:19 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 10:35:19 | INFO | stdout | [32mINFO[0m:     192.168.110.131:56214 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:35:30 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 10:35:30 | INFO | stdout | [32mINFO[0m:     192.168.110.131:47818 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 10:35:43 | WARNING | controller | Sending SIGKILL to {'zhipu-api': <Process name='api_worker - zhipu-api (1574803)' pid=1574803 parent=1573977 started daemon>}
2024-07-18 10:35:43 | WARNING | controller | Sending SIGKILL to {'chatglm3-6b': <Process name='model_worker - chatglm3-6b (1574802)' pid=1574802 parent=1573977 started daemon>}
2024-07-18 10:35:43 | WARNING | controller | Sending SIGKILL to <Process name='controller (1574557)' pid=1574557 parent=1573977 started daemon>
2024-07-18 10:35:43 | WARNING | controller | Sending SIGKILL to <Process name='openai_api (1574801)' pid=1574801 parent=1573977 started daemon>
2024-07-18 10:35:43 | WARNING | controller | Sending SIGKILL to <Process name='API Server (1575525)' pid=1575525 parent=1573977 started daemon>
2024-07-18 10:35:43 | INFO | controller | Process status: {'zhipu-api': <Process name='api_worker - zhipu-api (1574803)' pid=1574803 parent=1573977 started daemon>}
2024-07-18 10:35:43 | INFO | controller | Process status: {'chatglm3-6b': <Process name='model_worker - chatglm3-6b (1574802)' pid=1574802 parent=1573977 started daemon>}
2024-07-18 10:35:43 | INFO | controller | Process status: <Process name='controller (1574557)' pid=1574557 parent=1573977 started daemon>
2024-07-18 10:35:43 | INFO | controller | Process status: <Process name='openai_api (1574801)' pid=1574801 parent=1573977 started daemon>
2024-07-18 10:35:43 | INFO | controller | Process status: <Process name='API Server (1575525)' pid=1575525 parent=1573977 started daemon>
2024-07-18 10:35:43 | ERROR | stderr | Traceback (most recent call last):
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 584, in <module>
2024-07-18 10:35:43 | ERROR | stderr |     loop.run_until_complete(start_main_server())
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 495, in start_main_server
2024-07-18 10:35:43 | ERROR | stderr |     cmd = queue.get()
2024-07-18 10:35:43 | ERROR | stderr |   File "<string>", line 2, in get
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
2024-07-18 10:35:43 | ERROR | stderr |     kind, result = conn.recv()
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 255, in recv
2024-07-18 10:35:43 | ERROR | stderr |     buf = self._recv_bytes()
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
2024-07-18 10:35:43 | ERROR | stderr |     buf = self._recv(4)
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 384, in _recv
2024-07-18 10:35:43 | ERROR | stderr |     chunk = read(handle, remaining)
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 368, in f
2024-07-18 10:35:43 | ERROR | stderr |     raise KeyboardInterrupt(f"{signalname} received")
2024-07-18 10:35:43 | ERROR | stderr | KeyboardInterrupt: SIGINT received
2024-07-18 10:35:43 | ERROR | stderr | Exception ignored in atexit callback: <function _exit_function at 0x7fbd35451630>
2024-07-18 10:35:43 | ERROR | stderr | Traceback (most recent call last):
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/util.py", line 334, in _exit_function
2024-07-18 10:35:43 | ERROR | stderr |     _run_finalizers(0)
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
2024-07-18 10:35:43 | ERROR | stderr |     finalizer()
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/util.py", line 224, in __call__
2024-07-18 10:35:43 | ERROR | stderr |     res = self._callback(*self._args, **self._kwargs)
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/managers.py", line 674, in _finalize_manager
2024-07-18 10:35:43 | ERROR | stderr |     process.join(timeout=1.0)
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/process.py", line 149, in join
2024-07-18 10:35:43 | ERROR | stderr |     res = self._popen.wait(timeout)
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
2024-07-18 10:35:43 | ERROR | stderr |     if not wait([self.sentinel], timeout):
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 936, in wait
2024-07-18 10:35:43 | ERROR | stderr |     ready = selector.select(timeout)
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/selectors.py", line 416, in select
2024-07-18 10:35:43 | ERROR | stderr |     fd_event_list = self._selector.poll(timeout)
2024-07-18 10:35:43 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 368, in f
2024-07-18 10:35:43 | ERROR | stderr |     raise KeyboardInterrupt(f"{signalname} received")
2024-07-18 10:35:43 | ERROR | stderr | KeyboardInterrupt: SIGINT received
2024-07-18 11:34:31 | INFO | controller | 正在启动服务：
2024-07-18 11:34:31 | INFO | controller | 如需查看 服务日志 日志，请前往 /home/00_rag/fufan-chat-api/logs
2024-07-18 11:34:42 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1627172[0m]
2024-07-18 11:34:42 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 11:34:42 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 11:34:42 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:20001[0m (Press CTRL+C to quit)
2024-07-18 11:34:54 | INFO | controller | Register a new worker: http://192.168.110.131:21001
2024-07-18 11:34:54 | INFO | controller | Register done: http://192.168.110.131:21001, {'model_names': ['zhipu-api'], 'speed': 1, 'queue_length': 0}
2024-07-18 11:34:54 | INFO | stdout | [32mINFO[0m:     192.168.110.131:50308 - "[1mPOST /register_worker HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:34:54 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1627408[0m]
2024-07-18 11:34:54 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 11:34:54 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 11:34:54 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:20000[0m (Press CTRL+C to quit)
2024-07-18 11:34:54 | ERROR | stderr | Loading checkpoint shards:   0%|                                                                                                                                                                                                                                                          | 0/7 [00:00<?, ?it/s]
2024-07-18 11:34:55 | ERROR | stderr | Loading checkpoint shards:  14%|██████████████████████████████████▌                                                                                                                                                                                                               | 1/7 [00:00<00:03,  1.89it/s]
2024-07-18 11:34:55 | ERROR | stderr | Loading checkpoint shards:  29%|█████████████████████████████████████████████████████████████████████▏                                                                                                                                                                            | 2/7 [00:01<00:02,  1.91it/s]
2024-07-18 11:34:56 | ERROR | stderr | Loading checkpoint shards:  43%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                          | 3/7 [00:01<00:02,  1.99it/s]
2024-07-18 11:34:56 | ERROR | stderr | Loading checkpoint shards:  57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                       | 4/7 [00:01<00:01,  2.06it/s]
2024-07-18 11:34:57 | ERROR | stderr | Loading checkpoint shards:  71%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                     | 5/7 [00:02<00:00,  2.04it/s]
2024-07-18 11:34:57 | ERROR | stderr | Loading checkpoint shards:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 6/7 [00:02<00:00,  2.05it/s]
2024-07-18 11:34:58 | ERROR | stderr | Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.21it/s]
2024-07-18 11:34:58 | ERROR | stderr | Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.09it/s]
2024-07-18 11:34:58 | ERROR | stderr | 
2024-07-18 11:35:03 | INFO | controller | Register a new worker: http://192.168.110.131:20002
2024-07-18 11:35:03 | INFO | controller | Register done: http://192.168.110.131:20002, {'model_names': ['chatglm3-6b'], 'speed': 1, 'queue_length': 0}
2024-07-18 11:35:03 | INFO | stdout | [32mINFO[0m:     192.168.110.131:57364 - "[1mPOST /register_worker HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:35:03 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1627409[0m]
2024-07-18 11:35:03 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 11:35:03 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 11:35:03 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:20002[0m (Press CTRL+C to quit)
2024-07-18 11:35:14 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1628082[0m]
2024-07-18 11:35:14 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 11:35:14 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 11:35:14 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:8000[0m (Press CTRL+C to quit)
2024-07-18 11:35:27 | INFO | stdout | [32mINFO[0m:     192.168.110.91:58129 - "[1mPOST /api/chat/search_engine_chat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,768 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,768 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,770 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,771 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,772 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,772 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,775 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,808 INFO sqlalchemy.engine.Engine SELECT conversation.id AS conversation_id, conversation.user_id AS conversation_user_id, conversation.name AS conversation_name, conversation.chat_type AS conversation_chat_type, conversation.create_time AS conversation_create_time
2024-07-18 11:35:27 | INFO | stdout | FROM conversation
2024-07-18 11:35:27 | INFO | stdout | WHERE conversation.id = %s
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,809 INFO sqlalchemy.engine.Engine [generated in 0.00087s] ('dd27db58-3002-43d9-be59-675a95ab07bb',)
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,811 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,813 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,818 INFO sqlalchemy.engine.Engine INSERT INTO message (id, conversation_id, chat_type, query, response, meta_data, feedback_score, feedback_reason, create_time) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, now())
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,819 INFO sqlalchemy.engine.Engine [generated in 0.00072s] ('bee1227d-debe-43f2-9732-5fb8cd7acb9c', 'dd27db58-3002-43d9-be59-675a95ab07bb', 'real_time_search', ' 保罗乔治加盟了哪支NBA球队？', '', '{}', -1, '')
2024-07-18 11:35:27 | INFO | stdout | 2024-07-18 11:35:27,821 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:35:30 | INFO | stdout | 请求 URL 失败 https://zh.wikipedia.org/zh-hans/%E4%BF%9D%E7%BD%97%C2%B7%E4%B9%94%E6%B2%BB: Connection timeout to host https://zh.wikipedia.org/zh-hans/%E4%BF%9D%E7%BD%97%C2%B7%E4%B9%94%E6%B2%BB
2024-07-18 11:35:30 | INFO | stdout | -----------------------------
2024-07-18 11:35:30 | INFO | stdout | [Document(page_content='__\n\n#  保罗乔治加盟76人，宣称与恩比德是NBA最强组合\n\n__\n\n搞笑的壳子  原创 ·  2024-07-04 08:35   · 体育领域优质创作者\n\n点击查看更多订阅内容>\n\n保罗乔治最近以一份价值2亿美金的4年合同加盟了费城76人队，与恩比德携手组成了一支令人瞩目的双人组合。除了这两位顶尖球员之外，队中还有着新星马克西的加盟，使得该球队看起来已经具备了冲击总冠军的实力。保罗乔治在加盟76人后展现出前所未有的自信心。\n\n在一档播客节目中，保罗乔治坦言：“当我告别快船队时，我心中有些不舍。但由于快船队没有给予我足够的尊重，我也就没有再留在那里的必要。对我来说，加盟76人是最明智的选择。在这里，我不仅可以获得更多财富，还有望夺得总冠军。新赛季，没有球队愿意迎战76人。是的，我和恩比德构成了NBA最强大的组合，没有人可以阻止我们的成功。只要保持健康，我们就有机会夺冠。”\n\n随后，保罗乔治透露：“组建好和恩比德的组合后，詹姆斯呼我问为何不选择湖人队合作。他渴望与我并肩作战。我告诉他，湖人队无法满足我的要求。接着，追梦和格林也分别联系我。他们对我未加盟勇士队感到遗憾。总的来说，如今许多球队都希望我加入，但我只会选择对我最有利的决定。”乔治的言论引发了网上的热议，许多球迷纷纷表示，尽管76人实力强大，但尚未完全具备夺冠实力，而乔治和恩比德的组合也并非NBA最强。至少詹姆斯和浓眉的组合要比你们更胜一筹。\n\n发布于：广东省', metadata={'uuid': 'c99f6d04f076d93d890af98c7cd18676', 'title': '保罗乔治加盟76人，宣称与恩比德是NBA最强组合 - 手机搜狐', 'snippet': '保罗乔治最近以一份价值2亿美金的4年合同加盟了费城76人队，与恩比德携手组成了一支令人瞩目的双人组合。除了这两位顶尖球员之外，队中还有着新星马克 ...', 'link': 'https://m.sohu.com/a/790589954_121630157', 'score': '0.11842105263157898'}), Document(page_content='*   * 新闻\n  * 体育\n  * 汽车\n  * 房产\n  * 旅游\n  * 教育\n  * 时尚\n  * 科技\n  * 财经\n  * 娱乐\n  * 更多 __\n\n母婴 健康 历史 军事 美食 文化 星座 专题 游戏 搞笑 动漫 宠物\n\n无障碍 关怀版\n\n####  春在溪头 __\n\n由内容质量、互动评论、分享传播等多维度分值决定，勋章级别越高(  )，代表其在平台内的综合表现越好。\n\n    __文章\n    __总阅读\n\n  * 体育领域优质创作者\n\n查看TA的文章>\n\n评论\n\n    __\n\n#  原创 NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战\n\n2024-07-03 07:10\n\n发布于：广东省\n\n经过NBA交易市场的波动，一则官方公告突如其来，立刻在篮球界掀起轩然大波。曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。\n\n保罗·乔治作为联盟顶尖小前锋，其职业生涯充满传奇色彩。从印第安纳步行者队的崛起，到洛杉矶快船队的辉煌，再到如今的新东家，乔治每一步都牵动着无数球迷的心弦。他的球风刚劲、技术全面，在外线投射和内线突破方面都展现出极高水准。更为关键的是，他怀有永不言败的心态，总能在关键时刻挺身而出，为球队带来胜利。\n\n在被勇士队裁掉前，乔治已在联盟中演绎了多年。尽管无法助球队夺冠，他依旧热爱篮球、渴望胜利。得知被裁后，他并未消沉，而是迅速调整心态，开始探寻新出路。', metadata={'uuid': '56f49c359c1f2c9b5ad5d66d94718e3b', 'title': '原创NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战 - 搜狐', 'snippet': '曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。更为关键的是，他怀有永不言败的心态 ...', 'link': 'https://www.sohu.com/a/790283805_121926163', 'score': '0.07894736842105265'}), Document(page_content='在被勇士队裁掉前，乔治已在联盟中演绎了多年。尽管无法助球队夺冠，他依旧热爱篮球、渴望胜利。得知被裁后，他并未消沉，而是迅速调整心态，开始探寻新出路。\n\n就在此时，一支拥有多位超巨的豪强球队向乔治招手。该队众强阵容深厚底蕴，怀抱冠军梦想，而乔治也对这支球队充满兴趣，视其为实现冠军梦想的最佳平台。经深思熟虑，乔治决定与该队签约，正式加入他们的行列。\n\n随着乔治的加盟，该队实力大幅提升。聚集一众顶尖球员，包括超级巨星、得分高手、防守专才等，各具特长，能形成完美化学反应。在乔治领军下，该队将展现更强大战力，成为联盟不可忽视的一股力量。\n\n对乔治而言，加盟新东家意味着面对新挑战、新机遇。他将与多位超巨联手，共同冲击总冠军。在过程中，须适应新战术体系，与队友建立默契配合，关键时刻挺身而出，为球队斩获胜利。他已做好充分准备，坚信个人实力和经验能助球队圆冠梦。\n\n对球迷而言，乔治的加盟无疑是巨大惊喜。期待他在新队中有更耀眼表现，相信在其引领下，该队必将成为联盟强队，为球迷带来更多精彩对决、难忘瞬间。\n\n回顾乔治职业生涯，他一直怀着热爱篮球、追求卓越。无论在步行者队或快船队，为球队贡献巨大。现加盟新东家，将继续传承传奇。未来，愿共同见证乔治与队友书写新篇章。您如何看待这一切？欢迎留言评论！\n__返回搜狐，查看更多\n\n责任编辑：\n\n平台声明：该文观点仅代表作者本人，搜狐号系信息发布平台，搜狐仅提供信息存储空间服务。\n\n阅读 (__)\n\n__推荐阅读', metadata={'uuid': '56f49c359c1f2c9b5ad5d66d94718e3b', 'title': '原创NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战 - 搜狐', 'snippet': '曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。更为关键的是，他怀有永不言败的心态 ...', 'link': 'https://www.sohu.com/a/790283805_121926163', 'score': '0.07894736842105265'})]
2024-07-18 11:35:38 | INFO | stdout | 2024-07-18 11:35:38,207 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:35:38 | INFO | stdout | 2024-07-18 11:35:38,210 INFO sqlalchemy.engine.Engine SELECT message.id, message.conversation_id, message.chat_type, message.query, message.response, message.meta_data, message.feedback_score, message.feedback_reason, message.create_time
2024-07-18 11:35:38 | INFO | stdout | FROM message
2024-07-18 11:35:38 | INFO | stdout | WHERE message.conversation_id = %s AND message.chat_type = %s AND message.response != %s ORDER BY message.create_time DESC
2024-07-18 11:35:38 | INFO | stdout |  LIMIT %s
2024-07-18 11:35:38 | INFO | stdout | 2024-07-18 11:35:38,211 INFO sqlalchemy.engine.Engine [generated in 0.00087s] ('dd27db58-3002-43d9-be59-675a95ab07bb', 'real_time_search', '', 10)
2024-07-18 11:35:38 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2024-07-18 11:35:38 | ERROR | stderr | Traceback (most recent call last):
2024-07-18 11:35:38 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 284, in __call__
2024-07-18 11:35:38 | ERROR | stderr |     await wrap(partial(self.listen_for_disconnect, receive))
2024-07-18 11:35:38 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 273, in wrap
2024-07-18 11:35:38 | ERROR | stderr |     await func()
2024-07-18 11:35:38 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 223, in listen_for_disconnect
2024-07-18 11:35:38 | ERROR | stderr |     message = await receive()
2024-07-18 11:35:38 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
2024-07-18 11:35:38 | ERROR | stderr |     await self.message_event.wait()
2024-07-18 11:35:38 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/asyncio/locks.py", line 213, in wait
2024-07-18 11:35:38 | ERROR | stderr |     await fut
2024-07-18 11:35:38 | ERROR | stderr | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7feea7b97af0
2024-07-18 11:35:38 | ERROR | stderr | 
2024-07-18 11:35:38 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-07-18 11:35:38 | ERROR | stderr | 
2024-07-18 11:35:38 | ERROR | stderr |   + Exception Group Traceback (most recent call last):
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-18 11:35:38 | ERROR | stderr |   |     result = await app(  # type: ignore[func-returns-value]
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-18 11:35:38 | ERROR | stderr |   |     return await self.app(scope, receive, send)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-18 11:35:38 | ERROR | stderr |   |     await super().__call__(scope, receive, send)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-07-18 11:35:38 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-18 11:35:38 | ERROR | stderr |   |     raise exc
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-18 11:35:38 | ERROR | stderr |   |     await self.app(scope, receive, _send)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-18 11:35:38 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-18 11:35:38 | ERROR | stderr |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-18 11:35:38 | ERROR | stderr |   |     raise exc
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-18 11:35:38 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
2024-07-18 11:35:38 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
2024-07-18 11:35:38 | ERROR | stderr |   |     await route.handle(scope, receive, send)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
2024-07-18 11:35:38 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
2024-07-18 11:35:38 | ERROR | stderr |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-18 11:35:38 | ERROR | stderr |   |     raise exc
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-18 11:35:38 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
2024-07-18 11:35:38 | ERROR | stderr |   |     await response(scope, receive, send)
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 270, in __call__
2024-07-18 11:35:38 | ERROR | stderr |   |     async with anyio.create_task_group() as task_group:
2024-07-18 11:35:38 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
2024-07-18 11:35:38 | ERROR | stderr |   |     raise BaseExceptionGroup(
2024-07-18 11:35:38 | ERROR | stderr |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-07-18 11:35:38 | ERROR | stderr |   +-+---------------- 1 ----------------
2024-07-18 11:35:38 | ERROR | stderr |     | Traceback (most recent call last):
2024-07-18 11:35:38 | ERROR | stderr |     |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 273, in wrap
2024-07-18 11:35:38 | ERROR | stderr |     |     await func()
2024-07-18 11:35:38 | ERROR | stderr |     |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 253, in stream_response
2024-07-18 11:35:38 | ERROR | stderr |     |     async for data in self.body_iterator:
2024-07-18 11:35:38 | ERROR | stderr |     |   File "/home/00_rag/fufan-chat-api/server/chat/search_engine_chat.py", line 134, in search_engine_chat_iterator
2024-07-18 11:35:38 | ERROR | stderr |     |     if stream:
2024-07-18 11:35:38 | ERROR | stderr |     | NameError: name 'stream' is not defined
2024-07-18 11:35:38 | ERROR | stderr |     +------------------------------------
2024-07-18 11:35:38 | INFO | stdout | 2024-07-18 11:35:38,225 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:35:38 | INFO | stdout | [32mINFO[0m:     192.168.110.131:54022 - "[1mPOST /list_models HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:35:38 | INFO | controller | names: ['http://192.168.110.131:20002'], queue_lens: [0.0], ret: http://192.168.110.131:20002
2024-07-18 11:35:38 | INFO | stdout | [32mINFO[0m:     192.168.110.131:54036 - "[1mPOST /get_worker_address HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:35:38 | INFO | stdout | [32mINFO[0m:     192.168.110.131:39174 - "[1mPOST /worker_get_conv_template HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:35:38 | INFO | stdout | [32mINFO[0m:     192.168.110.131:39180 - "[1mPOST /model_details HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:35:38 | INFO | stdout | [32mINFO[0m:     192.168.110.131:39196 - "[1mPOST /count_token HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:35:38 | INFO | stdout | [32mINFO[0m:     192.168.110.131:40888 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:35:38 | INFO | stdout | [32mINFO[0m:     192.168.110.131:39202 - "[1mPOST /worker_generate_stream HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:35:39 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 11:35:39 | INFO | stdout | [32mINFO[0m:     192.168.110.131:54048 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:35:41 | INFO | stdout | 2024-07-18 11:35:41,779 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:35:41 | INFO | stdout | 2024-07-18 11:35:41,781 INFO sqlalchemy.engine.Engine SELECT message.id, message.conversation_id, message.chat_type, message.query, message.response, message.meta_data, message.feedback_score, message.feedback_reason, message.create_time
2024-07-18 11:35:41 | INFO | stdout | FROM message
2024-07-18 11:35:41 | INFO | stdout | WHERE message.id = %s
2024-07-18 11:35:41 | INFO | stdout | 2024-07-18 11:35:41,782 INFO sqlalchemy.engine.Engine [generated in 0.00103s] ('bee1227d-debe-43f2-9732-5fb8cd7acb9c',)
2024-07-18 11:35:41 | INFO | stdout | 2024-07-18 11:35:41,785 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:35:41 | INFO | stdout | 2024-07-18 11:35:41,787 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:35:41 | INFO | stdout | 2024-07-18 11:35:41,790 INFO sqlalchemy.engine.Engine UPDATE message SET response=%s WHERE message.id = %s
2024-07-18 11:35:41 | INFO | stdout | 2024-07-18 11:35:41,790 INFO sqlalchemy.engine.Engine [generated in 0.00062s] ('保罗乔治加盟了费城76人队。', 'bee1227d-debe-43f2-9732-5fb8cd7acb9c')
2024-07-18 11:35:41 | INFO | stdout | 2024-07-18 11:35:41,792 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:35:48 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 11:35:48 | INFO | stdout | [32mINFO[0m:     192.168.110.131:45490 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:36:24 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 11:36:24 | INFO | stdout | [32mINFO[0m:     192.168.110.131:46818 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:36:33 | INFO | stdout | [32mINFO[0m:     192.168.110.91:58184 - "[1mPOST /api/chat/search_engine_chat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:36:33 | INFO | stdout | 2024-07-18 11:36:33,089 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:36:33 | INFO | stdout | 2024-07-18 11:36:33,090 INFO sqlalchemy.engine.Engine SELECT conversation.id AS conversation_id, conversation.user_id AS conversation_user_id, conversation.name AS conversation_name, conversation.chat_type AS conversation_chat_type, conversation.create_time AS conversation_create_time
2024-07-18 11:36:33 | INFO | stdout | FROM conversation
2024-07-18 11:36:33 | INFO | stdout | WHERE conversation.id = %s
2024-07-18 11:36:33 | INFO | stdout | 2024-07-18 11:36:33,091 INFO sqlalchemy.engine.Engine [cached since 65.28s ago] ('dd27db58-3002-43d9-be59-675a95ab07bb',)
2024-07-18 11:36:33 | INFO | stdout | 2024-07-18 11:36:33,094 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:36:33 | INFO | stdout | 2024-07-18 11:36:33,096 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:36:33 | INFO | stdout | 2024-07-18 11:36:33,097 INFO sqlalchemy.engine.Engine INSERT INTO message (id, conversation_id, chat_type, query, response, meta_data, feedback_score, feedback_reason, create_time) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, now())
2024-07-18 11:36:33 | INFO | stdout | 2024-07-18 11:36:33,098 INFO sqlalchemy.engine.Engine [cached since 65.28s ago] ('2c94c9cd-a993-48df-82e7-ac0928bd4ada', 'dd27db58-3002-43d9-be59-675a95ab07bb', 'real_time_search', ' 保罗乔治加盟了哪支NBA球队？', '', '{}', -1, '')
2024-07-18 11:36:33 | INFO | stdout | 2024-07-18 11:36:33,100 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:36:33 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 11:36:33 | INFO | stdout | [32mINFO[0m:     192.168.110.131:35460 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:36:35 | INFO | stdout | 请求 URL 失败 https://zh.wikipedia.org/zh-hans/%E4%BF%9D%E7%BD%97%C2%B7%E4%B9%94%E6%B2%BB: Connection timeout to host https://zh.wikipedia.org/zh-hans/%E4%BF%9D%E7%BD%97%C2%B7%E4%B9%94%E6%B2%BB
2024-07-18 11:36:35 | INFO | stdout | -----------------------------
2024-07-18 11:36:35 | INFO | stdout | [Document(page_content='__\n\n#  保罗乔治加盟76人，宣称与恩比德是NBA最强组合\n\n__\n\n搞笑的壳子  原创 ·  2024-07-04 08:35   · 体育领域优质创作者\n\n点击查看更多订阅内容>\n\n保罗乔治最近以一份价值2亿美金的4年合同加盟了费城76人队，与恩比德携手组成了一支令人瞩目的双人组合。除了这两位顶尖球员之外，队中还有着新星马克西的加盟，使得该球队看起来已经具备了冲击总冠军的实力。保罗乔治在加盟76人后展现出前所未有的自信心。\n\n在一档播客节目中，保罗乔治坦言：“当我告别快船队时，我心中有些不舍。但由于快船队没有给予我足够的尊重，我也就没有再留在那里的必要。对我来说，加盟76人是最明智的选择。在这里，我不仅可以获得更多财富，还有望夺得总冠军。新赛季，没有球队愿意迎战76人。是的，我和恩比德构成了NBA最强大的组合，没有人可以阻止我们的成功。只要保持健康，我们就有机会夺冠。”\n\n随后，保罗乔治透露：“组建好和恩比德的组合后，詹姆斯呼我问为何不选择湖人队合作。他渴望与我并肩作战。我告诉他，湖人队无法满足我的要求。接着，追梦和格林也分别联系我。他们对我未加盟勇士队感到遗憾。总的来说，如今许多球队都希望我加入，但我只会选择对我最有利的决定。”乔治的言论引发了网上的热议，许多球迷纷纷表示，尽管76人实力强大，但尚未完全具备夺冠实力，而乔治和恩比德的组合也并非NBA最强。至少詹姆斯和浓眉的组合要比你们更胜一筹。\n\n发布于：广东省', metadata={'uuid': 'c99f6d04f076d93d890af98c7cd18676', 'title': '保罗乔治加盟76人，宣称与恩比德是NBA最强组合 - 手机搜狐', 'snippet': '保罗乔治最近以一份价值2亿美金的4年合同加盟了费城76人队，与恩比德携手组成了一支令人瞩目的双人组合。除了这两位顶尖球员之外，队中还有着新星马克 ...', 'link': 'https://m.sohu.com/a/790589954_121630157', 'score': '0.11842105263157898'}), Document(page_content='*   * 新闻\n  * 体育\n  * 汽车\n  * 房产\n  * 旅游\n  * 教育\n  * 时尚\n  * 科技\n  * 财经\n  * 娱乐\n  * 更多 __\n\n母婴 健康 历史 军事 美食 文化 星座 专题 游戏 搞笑 动漫 宠物\n\n无障碍 关怀版\n\n####  春在溪头 __\n\n由内容质量、互动评论、分享传播等多维度分值决定，勋章级别越高(  )，代表其在平台内的综合表现越好。\n\n    __文章\n    __总阅读\n\n  * 体育领域优质创作者\n\n查看TA的文章>\n\n评论\n\n    __\n\n#  原创 NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战\n\n2024-07-03 07:10\n\n发布于：广东省\n\n经过NBA交易市场的波动，一则官方公告突如其来，立刻在篮球界掀起轩然大波。曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。\n\n保罗·乔治作为联盟顶尖小前锋，其职业生涯充满传奇色彩。从印第安纳步行者队的崛起，到洛杉矶快船队的辉煌，再到如今的新东家，乔治每一步都牵动着无数球迷的心弦。他的球风刚劲、技术全面，在外线投射和内线突破方面都展现出极高水准。更为关键的是，他怀有永不言败的心态，总能在关键时刻挺身而出，为球队带来胜利。\n\n在被勇士队裁掉前，乔治已在联盟中演绎了多年。尽管无法助球队夺冠，他依旧热爱篮球、渴望胜利。得知被裁后，他并未消沉，而是迅速调整心态，开始探寻新出路。', metadata={'uuid': '56f49c359c1f2c9b5ad5d66d94718e3b', 'title': '原创NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战 - 搜狐', 'snippet': '曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。更为关键的是，他怀有永不言败的心态 ...', 'link': 'https://www.sohu.com/a/790283805_121926163', 'score': '0.07894736842105265'}), Document(page_content='在被勇士队裁掉前，乔治已在联盟中演绎了多年。尽管无法助球队夺冠，他依旧热爱篮球、渴望胜利。得知被裁后，他并未消沉，而是迅速调整心态，开始探寻新出路。\n\n就在此时，一支拥有多位超巨的豪强球队向乔治招手。该队众强阵容深厚底蕴，怀抱冠军梦想，而乔治也对这支球队充满兴趣，视其为实现冠军梦想的最佳平台。经深思熟虑，乔治决定与该队签约，正式加入他们的行列。\n\n随着乔治的加盟，该队实力大幅提升。聚集一众顶尖球员，包括超级巨星、得分高手、防守专才等，各具特长，能形成完美化学反应。在乔治领军下，该队将展现更强大战力，成为联盟不可忽视的一股力量。\n\n对乔治而言，加盟新东家意味着面对新挑战、新机遇。他将与多位超巨联手，共同冲击总冠军。在过程中，须适应新战术体系，与队友建立默契配合，关键时刻挺身而出，为球队斩获胜利。他已做好充分准备，坚信个人实力和经验能助球队圆冠梦。\n\n对球迷而言，乔治的加盟无疑是巨大惊喜。期待他在新队中有更耀眼表现，相信在其引领下，该队必将成为联盟强队，为球迷带来更多精彩对决、难忘瞬间。\n\n回顾乔治职业生涯，他一直怀着热爱篮球、追求卓越。无论在步行者队或快船队，为球队贡献巨大。现加盟新东家，将继续传承传奇。未来，愿共同见证乔治与队友书写新篇章。您如何看待这一切？欢迎留言评论！\n__返回搜狐，查看更多\n\n责任编辑：\n\n平台声明：该文观点仅代表作者本人，搜狐号系信息发布平台，搜狐仅提供信息存储空间服务。\n\n阅读 (__)\n\n__推荐阅读', metadata={'uuid': '56f49c359c1f2c9b5ad5d66d94718e3b', 'title': '原创NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战 - 搜狐', 'snippet': '曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。更为关键的是，他怀有永不言败的心态 ...', 'link': 'https://www.sohu.com/a/790283805_121926163', 'score': '0.07894736842105265'})]
2024-07-18 11:36:36 | INFO | stdout | 2024-07-18 11:36:36,153 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:36:36 | INFO | stdout | 2024-07-18 11:36:36,153 INFO sqlalchemy.engine.Engine SELECT message.id, message.conversation_id, message.chat_type, message.query, message.response, message.meta_data, message.feedback_score, message.feedback_reason, message.create_time
2024-07-18 11:36:36 | INFO | stdout | FROM message
2024-07-18 11:36:36 | INFO | stdout | WHERE message.conversation_id = %s AND message.chat_type = %s AND message.response != %s ORDER BY message.create_time DESC
2024-07-18 11:36:36 | INFO | stdout |  LIMIT %s
2024-07-18 11:36:36 | INFO | stdout | 2024-07-18 11:36:36,154 INFO sqlalchemy.engine.Engine [cached since 57.94s ago] ('dd27db58-3002-43d9-be59-675a95ab07bb', 'real_time_search', '', 10)
2024-07-18 11:36:36 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2024-07-18 11:36:36 | ERROR | stderr | Traceback (most recent call last):
2024-07-18 11:36:36 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 284, in __call__
2024-07-18 11:36:36 | ERROR | stderr |     await wrap(partial(self.listen_for_disconnect, receive))
2024-07-18 11:36:36 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 273, in wrap
2024-07-18 11:36:36 | ERROR | stderr |     await func()
2024-07-18 11:36:36 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 223, in listen_for_disconnect
2024-07-18 11:36:36 | ERROR | stderr |     message = await receive()
2024-07-18 11:36:36 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
2024-07-18 11:36:36 | ERROR | stderr |     await self.message_event.wait()
2024-07-18 11:36:36 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/asyncio/locks.py", line 213, in wait
2024-07-18 11:36:36 | ERROR | stderr |     await fut
2024-07-18 11:36:36 | ERROR | stderr | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7feea8a726b0
2024-07-18 11:36:36 | ERROR | stderr | 
2024-07-18 11:36:36 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-07-18 11:36:36 | ERROR | stderr | 
2024-07-18 11:36:36 | ERROR | stderr |   + Exception Group Traceback (most recent call last):
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-18 11:36:36 | ERROR | stderr |   |     result = await app(  # type: ignore[func-returns-value]
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-18 11:36:36 | ERROR | stderr |   |     return await self.app(scope, receive, send)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-18 11:36:36 | ERROR | stderr |   |     await super().__call__(scope, receive, send)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-07-18 11:36:36 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-18 11:36:36 | ERROR | stderr |   |     raise exc
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-18 11:36:36 | ERROR | stderr |   |     await self.app(scope, receive, _send)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-18 11:36:36 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-18 11:36:36 | ERROR | stderr |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-18 11:36:36 | ERROR | stderr |   |     raise exc
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-18 11:36:36 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
2024-07-18 11:36:36 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
2024-07-18 11:36:36 | ERROR | stderr |   |     await route.handle(scope, receive, send)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
2024-07-18 11:36:36 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
2024-07-18 11:36:36 | ERROR | stderr |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-18 11:36:36 | ERROR | stderr |   |     raise exc
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-18 11:36:36 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
2024-07-18 11:36:36 | ERROR | stderr |   |     await response(scope, receive, send)
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 270, in __call__
2024-07-18 11:36:36 | ERROR | stderr |   |     async with anyio.create_task_group() as task_group:
2024-07-18 11:36:36 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
2024-07-18 11:36:36 | ERROR | stderr |   |     raise BaseExceptionGroup(
2024-07-18 11:36:36 | ERROR | stderr |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-07-18 11:36:36 | ERROR | stderr |   +-+---------------- 1 ----------------
2024-07-18 11:36:36 | ERROR | stderr |     | Traceback (most recent call last):
2024-07-18 11:36:36 | ERROR | stderr |     |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 273, in wrap
2024-07-18 11:36:36 | ERROR | stderr |     |     await func()
2024-07-18 11:36:36 | ERROR | stderr |     |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 253, in stream_response
2024-07-18 11:36:36 | ERROR | stderr |     |     async for data in self.body_iterator:
2024-07-18 11:36:36 | ERROR | stderr |     |   File "/home/00_rag/fufan-chat-api/server/chat/search_engine_chat.py", line 134, in search_engine_chat_iterator
2024-07-18 11:36:36 | ERROR | stderr |     |     if STREAM:
2024-07-18 11:36:36 | ERROR | stderr |     | NameError: name 'stream' is not defined
2024-07-18 11:36:36 | ERROR | stderr |     +------------------------------------
2024-07-18 11:36:36 | INFO | stdout | 2024-07-18 11:36:36,167 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:36:36 | INFO | stdout | [32mINFO[0m:     192.168.110.131:35470 - "[1mPOST /list_models HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:36:36 | INFO | controller | names: ['http://192.168.110.131:20002'], queue_lens: [0.0], ret: http://192.168.110.131:20002
2024-07-18 11:36:36 | INFO | stdout | [32mINFO[0m:     192.168.110.131:35484 - "[1mPOST /get_worker_address HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:36:36 | INFO | stdout | [32mINFO[0m:     192.168.110.131:51076 - "[1mPOST /model_details HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:36:36 | INFO | stdout | [32mINFO[0m:     192.168.110.131:51088 - "[1mPOST /count_token HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:36:36 | INFO | stdout | [32mINFO[0m:     192.168.110.131:41706 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:36:36 | INFO | stdout | [32mINFO[0m:     192.168.110.131:51092 - "[1mPOST /worker_generate_stream HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:36:37 | INFO | stdout | 2024-07-18 11:36:37,555 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:36:37 | INFO | stdout | 2024-07-18 11:36:37,556 INFO sqlalchemy.engine.Engine SELECT message.id, message.conversation_id, message.chat_type, message.query, message.response, message.meta_data, message.feedback_score, message.feedback_reason, message.create_time
2024-07-18 11:36:37 | INFO | stdout | FROM message
2024-07-18 11:36:37 | INFO | stdout | WHERE message.id = %s
2024-07-18 11:36:37 | INFO | stdout | 2024-07-18 11:36:37,556 INFO sqlalchemy.engine.Engine [cached since 55.78s ago] ('2c94c9cd-a993-48df-82e7-ac0928bd4ada',)
2024-07-18 11:36:37 | INFO | stdout | 2024-07-18 11:36:37,559 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:36:37 | INFO | stdout | 2024-07-18 11:36:37,561 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:36:37 | INFO | stdout | 2024-07-18 11:36:37,562 INFO sqlalchemy.engine.Engine UPDATE message SET response=%s WHERE message.id = %s
2024-07-18 11:36:37 | INFO | stdout | 2024-07-18 11:36:37,562 INFO sqlalchemy.engine.Engine [cached since 55.77s ago] ('保罗乔治加盟了费城76人队。', '2c94c9cd-a993-48df-82e7-ac0928bd4ada')
2024-07-18 11:36:37 | INFO | stdout | 2024-07-18 11:36:37,564 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:37:09 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 11:37:09 | INFO | stdout | [32mINFO[0m:     192.168.110.131:46380 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:37:18 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 11:37:18 | INFO | stdout | [32mINFO[0m:     192.168.110.131:53152 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:37:49 | INFO | stdout | [32mINFO[0m:     192.168.110.91:58225 - "[1mPOST /api/chat/search_engine_chat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:37:49 | INFO | stdout | 2024-07-18 11:37:49,476 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:37:49 | INFO | stdout | 2024-07-18 11:37:49,477 INFO sqlalchemy.engine.Engine SELECT conversation.id AS conversation_id, conversation.user_id AS conversation_user_id, conversation.name AS conversation_name, conversation.chat_type AS conversation_chat_type, conversation.create_time AS conversation_create_time
2024-07-18 11:37:49 | INFO | stdout | FROM conversation
2024-07-18 11:37:49 | INFO | stdout | WHERE conversation.id = %s
2024-07-18 11:37:49 | INFO | stdout | 2024-07-18 11:37:49,478 INFO sqlalchemy.engine.Engine [cached since 141.7s ago] ('dd27db58-3002-43d9-be59-675a95ab07bb',)
2024-07-18 11:37:49 | INFO | stdout | 2024-07-18 11:37:49,480 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:37:49 | INFO | stdout | 2024-07-18 11:37:49,483 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:37:49 | INFO | stdout | 2024-07-18 11:37:49,484 INFO sqlalchemy.engine.Engine INSERT INTO message (id, conversation_id, chat_type, query, response, meta_data, feedback_score, feedback_reason, create_time) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, now())
2024-07-18 11:37:49 | INFO | stdout | 2024-07-18 11:37:49,484 INFO sqlalchemy.engine.Engine [cached since 141.7s ago] ('0aa17ea5-53fc-4d5d-a7a3-555ebc655f64', 'dd27db58-3002-43d9-be59-675a95ab07bb', 'real_time_search', ' 保罗乔治加盟了哪支NBA球队？', '', '{}', -1, '')
2024-07-18 11:37:49 | INFO | stdout | 2024-07-18 11:37:49,486 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:37:52 | INFO | stdout | 请求 URL 失败 https://zh.wikipedia.org/zh-hans/%E4%BF%9D%E7%BD%97%C2%B7%E4%B9%94%E6%B2%BB: Connection timeout to host https://zh.wikipedia.org/zh-hans/%E4%BF%9D%E7%BD%97%C2%B7%E4%B9%94%E6%B2%BB
2024-07-18 11:37:52 | INFO | stdout | -----------------------------
2024-07-18 11:37:52 | INFO | stdout | [Document(page_content='__\n\n#  保罗乔治加盟76人，宣称与恩比德是NBA最强组合\n\n__\n\n搞笑的壳子  原创 ·  2024-07-04 08:35   · 体育领域优质创作者\n\n点击查看更多订阅内容>\n\n保罗乔治最近以一份价值2亿美金的4年合同加盟了费城76人队，与恩比德携手组成了一支令人瞩目的双人组合。除了这两位顶尖球员之外，队中还有着新星马克西的加盟，使得该球队看起来已经具备了冲击总冠军的实力。保罗乔治在加盟76人后展现出前所未有的自信心。\n\n在一档播客节目中，保罗乔治坦言：“当我告别快船队时，我心中有些不舍。但由于快船队没有给予我足够的尊重，我也就没有再留在那里的必要。对我来说，加盟76人是最明智的选择。在这里，我不仅可以获得更多财富，还有望夺得总冠军。新赛季，没有球队愿意迎战76人。是的，我和恩比德构成了NBA最强大的组合，没有人可以阻止我们的成功。只要保持健康，我们就有机会夺冠。”\n\n随后，保罗乔治透露：“组建好和恩比德的组合后，詹姆斯呼我问为何不选择湖人队合作。他渴望与我并肩作战。我告诉他，湖人队无法满足我的要求。接着，追梦和格林也分别联系我。他们对我未加盟勇士队感到遗憾。总的来说，如今许多球队都希望我加入，但我只会选择对我最有利的决定。”乔治的言论引发了网上的热议，许多球迷纷纷表示，尽管76人实力强大，但尚未完全具备夺冠实力，而乔治和恩比德的组合也并非NBA最强。至少詹姆斯和浓眉的组合要比你们更胜一筹。\n\n发布于：广东省', metadata={'uuid': 'c99f6d04f076d93d890af98c7cd18676', 'title': '保罗乔治加盟76人，宣称与恩比德是NBA最强组合 - 手机搜狐', 'snippet': '保罗乔治最近以一份价值2亿美金的4年合同加盟了费城76人队，与恩比德携手组成了一支令人瞩目的双人组合。除了这两位顶尖球员之外，队中还有着新星马克 ...', 'link': 'https://m.sohu.com/a/790589954_121630157', 'score': '0.11842105263157898'}), Document(page_content='*   * 新闻\n  * 体育\n  * 汽车\n  * 房产\n  * 旅游\n  * 教育\n  * 时尚\n  * 科技\n  * 财经\n  * 娱乐\n  * 更多 __\n\n母婴 健康 历史 军事 美食 文化 星座 专题 游戏 搞笑 动漫 宠物\n\n无障碍 关怀版\n\n####  春在溪头 __\n\n由内容质量、互动评论、分享传播等多维度分值决定，勋章级别越高(  )，代表其在平台内的综合表现越好。\n\n    __文章\n    __总阅读\n\n  * 体育领域优质创作者\n\n查看TA的文章>\n\n评论\n\n    __\n\n#  原创 NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战\n\n2024-07-03 07:10\n\n发布于：广东省\n\n经过NBA交易市场的波动，一则官方公告突如其来，立刻在篮球界掀起轩然大波。曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。\n\n保罗·乔治作为联盟顶尖小前锋，其职业生涯充满传奇色彩。从印第安纳步行者队的崛起，到洛杉矶快船队的辉煌，再到如今的新东家，乔治每一步都牵动着无数球迷的心弦。他的球风刚劲、技术全面，在外线投射和内线突破方面都展现出极高水准。更为关键的是，他怀有永不言败的心态，总能在关键时刻挺身而出，为球队带来胜利。\n\n在被勇士队裁掉前，乔治已在联盟中演绎了多年。尽管无法助球队夺冠，他依旧热爱篮球、渴望胜利。得知被裁后，他并未消沉，而是迅速调整心态，开始探寻新出路。', metadata={'uuid': '56f49c359c1f2c9b5ad5d66d94718e3b', 'title': '原创NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战 - 搜狐', 'snippet': '曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。更为关键的是，他怀有永不言败的心态 ...', 'link': 'https://www.sohu.com/a/790283805_121926163', 'score': '0.07894736842105265'}), Document(page_content='在被勇士队裁掉前，乔治已在联盟中演绎了多年。尽管无法助球队夺冠，他依旧热爱篮球、渴望胜利。得知被裁后，他并未消沉，而是迅速调整心态，开始探寻新出路。\n\n就在此时，一支拥有多位超巨的豪强球队向乔治招手。该队众强阵容深厚底蕴，怀抱冠军梦想，而乔治也对这支球队充满兴趣，视其为实现冠军梦想的最佳平台。经深思熟虑，乔治决定与该队签约，正式加入他们的行列。\n\n随着乔治的加盟，该队实力大幅提升。聚集一众顶尖球员，包括超级巨星、得分高手、防守专才等，各具特长，能形成完美化学反应。在乔治领军下，该队将展现更强大战力，成为联盟不可忽视的一股力量。\n\n对乔治而言，加盟新东家意味着面对新挑战、新机遇。他将与多位超巨联手，共同冲击总冠军。在过程中，须适应新战术体系，与队友建立默契配合，关键时刻挺身而出，为球队斩获胜利。他已做好充分准备，坚信个人实力和经验能助球队圆冠梦。\n\n对球迷而言，乔治的加盟无疑是巨大惊喜。期待他在新队中有更耀眼表现，相信在其引领下，该队必将成为联盟强队，为球迷带来更多精彩对决、难忘瞬间。\n\n回顾乔治职业生涯，他一直怀着热爱篮球、追求卓越。无论在步行者队或快船队，为球队贡献巨大。现加盟新东家，将继续传承传奇。未来，愿共同见证乔治与队友书写新篇章。您如何看待这一切？欢迎留言评论！\n__返回搜狐，查看更多\n\n责任编辑：\n\n平台声明：该文观点仅代表作者本人，搜狐号系信息发布平台，搜狐仅提供信息存储空间服务。\n\n阅读 (__)\n\n__推荐阅读', metadata={'uuid': '56f49c359c1f2c9b5ad5d66d94718e3b', 'title': '原创NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战 - 搜狐', 'snippet': '曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。更为关键的是，他怀有永不言败的心态 ...', 'link': 'https://www.sohu.com/a/790283805_121926163', 'score': '0.07894736842105265'})]
2024-07-18 11:37:52 | INFO | stdout | 2024-07-18 11:37:52,551 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:37:52 | INFO | stdout | 2024-07-18 11:37:52,551 INFO sqlalchemy.engine.Engine SELECT message.id, message.conversation_id, message.chat_type, message.query, message.response, message.meta_data, message.feedback_score, message.feedback_reason, message.create_time
2024-07-18 11:37:52 | INFO | stdout | FROM message
2024-07-18 11:37:52 | INFO | stdout | WHERE message.conversation_id = %s AND message.chat_type = %s AND message.response != %s ORDER BY message.create_time DESC
2024-07-18 11:37:52 | INFO | stdout |  LIMIT %s
2024-07-18 11:37:52 | INFO | stdout | 2024-07-18 11:37:52,552 INFO sqlalchemy.engine.Engine [cached since 134.3s ago] ('dd27db58-3002-43d9-be59-675a95ab07bb', 'real_time_search', '', 10)
2024-07-18 11:37:52 | ERROR | stderr | [31mERROR[0m:    Exception in ASGI application
2024-07-18 11:37:52 | ERROR | stderr | Traceback (most recent call last):
2024-07-18 11:37:52 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 284, in __call__
2024-07-18 11:37:52 | ERROR | stderr |     await wrap(partial(self.listen_for_disconnect, receive))
2024-07-18 11:37:52 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 273, in wrap
2024-07-18 11:37:52 | ERROR | stderr |     await func()
2024-07-18 11:37:52 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 223, in listen_for_disconnect
2024-07-18 11:37:52 | ERROR | stderr |     message = await receive()
2024-07-18 11:37:52 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
2024-07-18 11:37:52 | ERROR | stderr |     await self.message_event.wait()
2024-07-18 11:37:52 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/asyncio/locks.py", line 213, in wait
2024-07-18 11:37:52 | ERROR | stderr |     await fut
2024-07-18 11:37:52 | ERROR | stderr | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fee9441baf0
2024-07-18 11:37:52 | ERROR | stderr | 
2024-07-18 11:37:52 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-07-18 11:37:52 | ERROR | stderr | 
2024-07-18 11:37:52 | ERROR | stderr |   + Exception Group Traceback (most recent call last):
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
2024-07-18 11:37:52 | ERROR | stderr |   |     result = await app(  # type: ignore[func-returns-value]
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-07-18 11:37:52 | ERROR | stderr |   |     return await self.app(scope, receive, send)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-18 11:37:52 | ERROR | stderr |   |     await super().__call__(scope, receive, send)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-07-18 11:37:52 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-18 11:37:52 | ERROR | stderr |   |     raise exc
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-18 11:37:52 | ERROR | stderr |   |     await self.app(scope, receive, _send)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-18 11:37:52 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-18 11:37:52 | ERROR | stderr |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-18 11:37:52 | ERROR | stderr |   |     raise exc
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-18 11:37:52 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
2024-07-18 11:37:52 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
2024-07-18 11:37:52 | ERROR | stderr |   |     await route.handle(scope, receive, send)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
2024-07-18 11:37:52 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
2024-07-18 11:37:52 | ERROR | stderr |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-18 11:37:52 | ERROR | stderr |   |     raise exc
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-18 11:37:52 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
2024-07-18 11:37:52 | ERROR | stderr |   |     await response(scope, receive, send)
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 270, in __call__
2024-07-18 11:37:52 | ERROR | stderr |   |     async with anyio.create_task_group() as task_group:
2024-07-18 11:37:52 | ERROR | stderr |   |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
2024-07-18 11:37:52 | ERROR | stderr |   |     raise BaseExceptionGroup(
2024-07-18 11:37:52 | ERROR | stderr |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-07-18 11:37:52 | ERROR | stderr |   +-+---------------- 1 ----------------
2024-07-18 11:37:52 | ERROR | stderr |     | Traceback (most recent call last):
2024-07-18 11:37:52 | ERROR | stderr |     |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 273, in wrap
2024-07-18 11:37:52 | ERROR | stderr |     |     await func()
2024-07-18 11:37:52 | ERROR | stderr |     |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/site-packages/sse_starlette/sse.py", line 253, in stream_response
2024-07-18 11:37:52 | ERROR | stderr |     |     async for data in self.body_iterator:
2024-07-18 11:37:52 | ERROR | stderr |     |   File "/home/00_rag/fufan-chat-api/server/chat/search_engine_chat.py", line 134, in search_engine_chat_iterator
2024-07-18 11:37:52 | ERROR | stderr |     |     if STREAM:
2024-07-18 11:37:52 | ERROR | stderr |     | NameError: name 'stream' is not defined
2024-07-18 11:37:52 | ERROR | stderr |     +------------------------------------
2024-07-18 11:37:52 | INFO | stdout | 2024-07-18 11:37:52,560 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:37:52 | INFO | stdout | [32mINFO[0m:     192.168.110.131:35224 - "[1mPOST /list_models HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:37:52 | INFO | controller | names: ['http://192.168.110.131:20002'], queue_lens: [0.0], ret: http://192.168.110.131:20002
2024-07-18 11:37:52 | INFO | stdout | [32mINFO[0m:     192.168.110.131:35226 - "[1mPOST /get_worker_address HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:37:52 | INFO | stdout | [32mINFO[0m:     192.168.110.131:50038 - "[1mPOST /model_details HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:37:52 | INFO | stdout | [32mINFO[0m:     192.168.110.131:50044 - "[1mPOST /count_token HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:37:52 | INFO | stdout | [32mINFO[0m:     192.168.110.131:46404 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:37:52 | INFO | stdout | [32mINFO[0m:     192.168.110.131:50058 - "[1mPOST /worker_generate_stream HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:37:53 | INFO | stdout | 2024-07-18 11:37:53,400 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:37:53 | INFO | stdout | 2024-07-18 11:37:53,401 INFO sqlalchemy.engine.Engine SELECT message.id, message.conversation_id, message.chat_type, message.query, message.response, message.meta_data, message.feedback_score, message.feedback_reason, message.create_time
2024-07-18 11:37:53 | INFO | stdout | FROM message
2024-07-18 11:37:53 | INFO | stdout | WHERE message.id = %s
2024-07-18 11:37:53 | INFO | stdout | 2024-07-18 11:37:53,401 INFO sqlalchemy.engine.Engine [cached since 131.6s ago] ('0aa17ea5-53fc-4d5d-a7a3-555ebc655f64',)
2024-07-18 11:37:53 | INFO | stdout | 2024-07-18 11:37:53,404 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:37:53 | INFO | stdout | 2024-07-18 11:37:53,406 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:37:53 | INFO | stdout | 2024-07-18 11:37:53,407 INFO sqlalchemy.engine.Engine UPDATE message SET response=%s WHERE message.id = %s
2024-07-18 11:37:53 | INFO | stdout | 2024-07-18 11:37:53,407 INFO sqlalchemy.engine.Engine [cached since 131.6s ago] ('根据我取得的最新信息，保罗·乔治加盟了洛杉矶快船队。', '0aa17ea5-53fc-4d5d-a7a3-555ebc655f64')
2024-07-18 11:37:53 | INFO | stdout | 2024-07-18 11:37:53,409 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:37:54 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 11:37:54 | INFO | stdout | [32mINFO[0m:     192.168.110.131:35238 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:38:03 | WARNING | controller | Sending SIGKILL to {'zhipu-api': <Process name='api_worker - zhipu-api (1627410)' pid=1627410 parent=1626615 started daemon>}
2024-07-18 11:38:03 | WARNING | controller | Sending SIGKILL to {'chatglm3-6b': <Process name='model_worker - chatglm3-6b (1627409)' pid=1627409 parent=1626615 started daemon>}
2024-07-18 11:38:03 | WARNING | controller | Sending SIGKILL to <Process name='controller (1627172)' pid=1627172 parent=1626615 started daemon>
2024-07-18 11:38:03 | WARNING | controller | Sending SIGKILL to <Process name='openai_api (1627408)' pid=1627408 parent=1626615 started daemon>
2024-07-18 11:38:03 | WARNING | controller | Sending SIGKILL to <Process name='API Server (1628082)' pid=1628082 parent=1626615 started daemon>
2024-07-18 11:38:03 | INFO | controller | Process status: {'zhipu-api': <Process name='api_worker - zhipu-api (1627410)' pid=1627410 parent=1626615 started daemon>}
2024-07-18 11:38:03 | INFO | controller | Process status: {'chatglm3-6b': <Process name='model_worker - chatglm3-6b (1627409)' pid=1627409 parent=1626615 started daemon>}
2024-07-18 11:38:03 | INFO | controller | Process status: <Process name='controller (1627172)' pid=1627172 parent=1626615 started daemon>
2024-07-18 11:38:03 | INFO | controller | Process status: <Process name='openai_api (1627408)' pid=1627408 parent=1626615 started daemon>
2024-07-18 11:38:03 | INFO | controller | Process status: <Process name='API Server (1628082)' pid=1628082 parent=1626615 started daemon>
2024-07-18 11:38:03 | ERROR | stderr | Traceback (most recent call last):
2024-07-18 11:38:03 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 584, in <module>
2024-07-18 11:38:03 | ERROR | stderr |     loop.run_until_complete(start_main_server())
2024-07-18 11:38:03 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 495, in start_main_server
2024-07-18 11:38:03 | ERROR | stderr |     cmd = queue.get()
2024-07-18 11:38:03 | ERROR | stderr |   File "<string>", line 2, in get
2024-07-18 11:38:03 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
2024-07-18 11:38:03 | ERROR | stderr |     kind, result = conn.recv()
2024-07-18 11:38:03 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 255, in recv
2024-07-18 11:38:03 | ERROR | stderr |     buf = self._recv_bytes()
2024-07-18 11:38:03 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
2024-07-18 11:38:03 | ERROR | stderr |     buf = self._recv(4)
2024-07-18 11:38:03 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 384, in _recv
2024-07-18 11:38:03 | ERROR | stderr |     chunk = read(handle, remaining)
2024-07-18 11:38:03 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 368, in f
2024-07-18 11:38:03 | ERROR | stderr |     raise KeyboardInterrupt(f"{signalname} received")
2024-07-18 11:38:03 | ERROR | stderr | KeyboardInterrupt: SIGINT received
2024-07-18 11:38:04 | ERROR | stderr | Exception ignored in atexit callback: <function _exit_function at 0x7f938be9d630>
2024-07-18 11:38:04 | ERROR | stderr | Traceback (most recent call last):
2024-07-18 11:38:04 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/util.py", line 334, in _exit_function
2024-07-18 11:38:04 | ERROR | stderr |     _run_finalizers(0)
2024-07-18 11:38:04 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
2024-07-18 11:38:04 | ERROR | stderr |     finalizer()
2024-07-18 11:38:04 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/util.py", line 224, in __call__
2024-07-18 11:38:04 | ERROR | stderr |     res = self._callback(*self._args, **self._kwargs)
2024-07-18 11:38:04 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/managers.py", line 674, in _finalize_manager
2024-07-18 11:38:04 | ERROR | stderr |     process.join(timeout=1.0)
2024-07-18 11:38:04 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/process.py", line 149, in join
2024-07-18 11:38:04 | ERROR | stderr |     res = self._popen.wait(timeout)
2024-07-18 11:38:04 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
2024-07-18 11:38:04 | ERROR | stderr |     if not wait([self.sentinel], timeout):
2024-07-18 11:38:04 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 936, in wait
2024-07-18 11:38:04 | ERROR | stderr |     ready = selector.select(timeout)
2024-07-18 11:38:04 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/selectors.py", line 416, in select
2024-07-18 11:38:04 | ERROR | stderr |     fd_event_list = self._selector.poll(timeout)
2024-07-18 11:38:04 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 368, in f
2024-07-18 11:38:04 | ERROR | stderr |     raise KeyboardInterrupt(f"{signalname} received")
2024-07-18 11:38:04 | ERROR | stderr | KeyboardInterrupt: SIGINT received
2024-07-18 11:38:28 | INFO | controller | 正在启动服务：
2024-07-18 11:38:28 | INFO | controller | 如需查看 服务日志 日志，请前往 /home/00_rag/fufan-chat-api/logs
2024-07-18 11:38:39 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1631760[0m]
2024-07-18 11:38:39 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 11:38:39 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 11:38:39 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:20001[0m (Press CTRL+C to quit)
2024-07-18 11:38:50 | INFO | controller | Register a new worker: http://192.168.110.131:21001
2024-07-18 11:38:50 | INFO | controller | Register done: http://192.168.110.131:21001, {'model_names': ['zhipu-api'], 'speed': 1, 'queue_length': 0}
2024-07-18 11:38:50 | INFO | stdout | [32mINFO[0m:     192.168.110.131:49128 - "[1mPOST /register_worker HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:38:51 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1632016[0m]
2024-07-18 11:38:51 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 11:38:51 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 11:38:51 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:20000[0m (Press CTRL+C to quit)
2024-07-18 11:38:51 | ERROR | stderr | Loading checkpoint shards:   0%|                                                                                                                                                                                                                                                          | 0/7 [00:00<?, ?it/s]
2024-07-18 11:38:51 | ERROR | stderr | Loading checkpoint shards:  14%|██████████████████████████████████▌                                                                                                                                                                                                               | 1/7 [00:00<00:03,  1.93it/s]
2024-07-18 11:38:52 | ERROR | stderr | Loading checkpoint shards:  29%|█████████████████████████████████████████████████████████████████████▏                                                                                                                                                                            | 2/7 [00:01<00:02,  1.90it/s]
2024-07-18 11:38:52 | ERROR | stderr | Loading checkpoint shards:  43%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                          | 3/7 [00:01<00:02,  1.98it/s]
2024-07-18 11:38:53 | ERROR | stderr | Loading checkpoint shards:  57%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                       | 4/7 [00:01<00:01,  2.06it/s]
2024-07-18 11:38:53 | ERROR | stderr | Loading checkpoint shards:  71%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                     | 5/7 [00:02<00:00,  2.04it/s]
2024-07-18 11:38:54 | ERROR | stderr | Loading checkpoint shards:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 6/7 [00:02<00:00,  2.05it/s]
2024-07-18 11:38:54 | ERROR | stderr | Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.21it/s]
2024-07-18 11:38:54 | ERROR | stderr | Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  2.09it/s]
2024-07-18 11:38:54 | ERROR | stderr | 
2024-07-18 11:39:00 | INFO | controller | Register a new worker: http://192.168.110.131:20002
2024-07-18 11:39:00 | INFO | controller | Register done: http://192.168.110.131:20002, {'model_names': ['chatglm3-6b'], 'speed': 1, 'queue_length': 0}
2024-07-18 11:39:00 | INFO | stdout | [32mINFO[0m:     192.168.110.131:56660 - "[1mPOST /register_worker HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:39:01 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1632017[0m]
2024-07-18 11:39:01 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 11:39:01 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 11:39:01 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:20002[0m (Press CTRL+C to quit)
2024-07-18 11:39:12 | ERROR | stderr | [32mINFO[0m:     Started server process [[36m1632838[0m]
2024-07-18 11:39:12 | ERROR | stderr | [32mINFO[0m:     Waiting for application startup.
2024-07-18 11:39:12 | ERROR | stderr | [32mINFO[0m:     Application startup complete.
2024-07-18 11:39:12 | ERROR | stderr | [32mINFO[0m:     Uvicorn running on [1mhttp://192.168.110.131:8000[0m (Press CTRL+C to quit)
2024-07-18 11:39:15 | INFO | stdout | [32mINFO[0m:     192.168.110.91:58434 - "[1mPOST /api/chat/search_engine_chat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,265 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,265 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,268 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,268 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,269 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,270 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,272 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,304 INFO sqlalchemy.engine.Engine SELECT conversation.id AS conversation_id, conversation.user_id AS conversation_user_id, conversation.name AS conversation_name, conversation.chat_type AS conversation_chat_type, conversation.create_time AS conversation_create_time
2024-07-18 11:39:15 | INFO | stdout | FROM conversation
2024-07-18 11:39:15 | INFO | stdout | WHERE conversation.id = %s
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,305 INFO sqlalchemy.engine.Engine [generated in 0.00099s] ('dd27db58-3002-43d9-be59-675a95ab07bb',)
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,308 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,310 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,315 INFO sqlalchemy.engine.Engine INSERT INTO message (id, conversation_id, chat_type, query, response, meta_data, feedback_score, feedback_reason, create_time) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, now())
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,316 INFO sqlalchemy.engine.Engine [generated in 0.00084s] ('86cfc90b-83c0-4eb9-9465-9dd3d33affc6', 'dd27db58-3002-43d9-be59-675a95ab07bb', 'real_time_search', ' 保罗乔治加盟了哪支NBA球队？', '', '{}', -1, '')
2024-07-18 11:39:15 | INFO | stdout | 2024-07-18 11:39:15,318 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:39:17 | INFO | stdout | 请求 URL 失败 https://zh.wikipedia.org/zh-hans/%E4%BF%9D%E7%BD%97%C2%B7%E4%B9%94%E6%B2%BB: Connection timeout to host https://zh.wikipedia.org/zh-hans/%E4%BF%9D%E7%BD%97%C2%B7%E4%B9%94%E6%B2%BB
2024-07-18 11:39:17 | INFO | stdout | -----------------------------
2024-07-18 11:39:17 | INFO | stdout | [Document(page_content='__\n\n#  保罗乔治加盟76人，宣称与恩比德是NBA最强组合\n\n__\n\n搞笑的壳子  原创 ·  2024-07-04 08:35   · 体育领域优质创作者\n\n点击查看更多订阅内容>\n\n保罗乔治最近以一份价值2亿美金的4年合同加盟了费城76人队，与恩比德携手组成了一支令人瞩目的双人组合。除了这两位顶尖球员之外，队中还有着新星马克西的加盟，使得该球队看起来已经具备了冲击总冠军的实力。保罗乔治在加盟76人后展现出前所未有的自信心。\n\n在一档播客节目中，保罗乔治坦言：“当我告别快船队时，我心中有些不舍。但由于快船队没有给予我足够的尊重，我也就没有再留在那里的必要。对我来说，加盟76人是最明智的选择。在这里，我不仅可以获得更多财富，还有望夺得总冠军。新赛季，没有球队愿意迎战76人。是的，我和恩比德构成了NBA最强大的组合，没有人可以阻止我们的成功。只要保持健康，我们就有机会夺冠。”\n\n随后，保罗乔治透露：“组建好和恩比德的组合后，詹姆斯呼我问为何不选择湖人队合作。他渴望与我并肩作战。我告诉他，湖人队无法满足我的要求。接着，追梦和格林也分别联系我。他们对我未加盟勇士队感到遗憾。总的来说，如今许多球队都希望我加入，但我只会选择对我最有利的决定。”乔治的言论引发了网上的热议，许多球迷纷纷表示，尽管76人实力强大，但尚未完全具备夺冠实力，而乔治和恩比德的组合也并非NBA最强。至少詹姆斯和浓眉的组合要比你们更胜一筹。\n\n发布于：广东省', metadata={'uuid': 'c99f6d04f076d93d890af98c7cd18676', 'title': '保罗乔治加盟76人，宣称与恩比德是NBA最强组合 - 手机搜狐', 'snippet': '保罗乔治最近以一份价值2亿美金的4年合同加盟了费城76人队，与恩比德携手组成了一支令人瞩目的双人组合。除了这两位顶尖球员之外，队中还有着新星马克 ...', 'link': 'https://m.sohu.com/a/790589954_121630157', 'score': '0.11842105263157898'}), Document(page_content='*   * 新闻\n  * 体育\n  * 汽车\n  * 房产\n  * 旅游\n  * 教育\n  * 时尚\n  * 科技\n  * 财经\n  * 娱乐\n  * 更多 __\n\n母婴 健康 历史 军事 美食 文化 星座 专题 游戏 搞笑 动漫 宠物\n\n无障碍 关怀版\n\n####  春在溪头 __\n\n由内容质量、互动评论、分享传播等多维度分值决定，勋章级别越高(  )，代表其在平台内的综合表现越好。\n\n    __文章\n    __总阅读\n\n  * 体育领域优质创作者\n\n查看TA的文章>\n\n评论\n\n    __\n\n#  原创 NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战\n\n2024-07-03 07:10\n\n发布于：广东省\n\n经过NBA交易市场的波动，一则官方公告突如其来，立刻在篮球界掀起轩然大波。曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。\n\n保罗·乔治作为联盟顶尖小前锋，其职业生涯充满传奇色彩。从印第安纳步行者队的崛起，到洛杉矶快船队的辉煌，再到如今的新东家，乔治每一步都牵动着无数球迷的心弦。他的球风刚劲、技术全面，在外线投射和内线突破方面都展现出极高水准。更为关键的是，他怀有永不言败的心态，总能在关键时刻挺身而出，为球队带来胜利。\n\n在被勇士队裁掉前，乔治已在联盟中演绎了多年。尽管无法助球队夺冠，他依旧热爱篮球、渴望胜利。得知被裁后，他并未消沉，而是迅速调整心态，开始探寻新出路。', metadata={'uuid': '56f49c359c1f2c9b5ad5d66d94718e3b', 'title': '原创NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战 - 搜狐', 'snippet': '曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。更为关键的是，他怀有永不言败的心态 ...', 'link': 'https://www.sohu.com/a/790283805_121926163', 'score': '0.07894736842105265'}), Document(page_content='在被勇士队裁掉前，乔治已在联盟中演绎了多年。尽管无法助球队夺冠，他依旧热爱篮球、渴望胜利。得知被裁后，他并未消沉，而是迅速调整心态，开始探寻新出路。\n\n就在此时，一支拥有多位超巨的豪强球队向乔治招手。该队众强阵容深厚底蕴，怀抱冠军梦想，而乔治也对这支球队充满兴趣，视其为实现冠军梦想的最佳平台。经深思熟虑，乔治决定与该队签约，正式加入他们的行列。\n\n随着乔治的加盟，该队实力大幅提升。聚集一众顶尖球员，包括超级巨星、得分高手、防守专才等，各具特长，能形成完美化学反应。在乔治领军下，该队将展现更强大战力，成为联盟不可忽视的一股力量。\n\n对乔治而言，加盟新东家意味着面对新挑战、新机遇。他将与多位超巨联手，共同冲击总冠军。在过程中，须适应新战术体系，与队友建立默契配合，关键时刻挺身而出，为球队斩获胜利。他已做好充分准备，坚信个人实力和经验能助球队圆冠梦。\n\n对球迷而言，乔治的加盟无疑是巨大惊喜。期待他在新队中有更耀眼表现，相信在其引领下，该队必将成为联盟强队，为球迷带来更多精彩对决、难忘瞬间。\n\n回顾乔治职业生涯，他一直怀着热爱篮球、追求卓越。无论在步行者队或快船队，为球队贡献巨大。现加盟新东家，将继续传承传奇。未来，愿共同见证乔治与队友书写新篇章。您如何看待这一切？欢迎留言评论！\n__返回搜狐，查看更多\n\n责任编辑：\n\n平台声明：该文观点仅代表作者本人，搜狐号系信息发布平台，搜狐仅提供信息存储空间服务。\n\n阅读 (__)\n\n__推荐阅读', metadata={'uuid': '56f49c359c1f2c9b5ad5d66d94718e3b', 'title': '原创NBA震撼！保罗·乔治下家揭晓，加盟豪强球队迎新挑战 - 搜狐', 'snippet': '曾经风采熠熠的NBA巨星保罗·乔治，在被勇士队裁掉仅一小时后，迅速与另一支豪强球队签约，正式确定了他的新归宿。更为关键的是，他怀有永不言败的心态 ...', 'link': 'https://www.sohu.com/a/790283805_121926163', 'score': '0.07894736842105265'})]
2024-07-18 11:39:22 | INFO | stdout | 2024-07-18 11:39:22,383 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:39:22 | INFO | stdout | 2024-07-18 11:39:22,386 INFO sqlalchemy.engine.Engine SELECT message.id, message.conversation_id, message.chat_type, message.query, message.response, message.meta_data, message.feedback_score, message.feedback_reason, message.create_time
2024-07-18 11:39:22 | INFO | stdout | FROM message
2024-07-18 11:39:22 | INFO | stdout | WHERE message.conversation_id = %s AND message.chat_type = %s AND message.response != %s ORDER BY message.create_time DESC
2024-07-18 11:39:22 | INFO | stdout |  LIMIT %s
2024-07-18 11:39:22 | INFO | stdout | 2024-07-18 11:39:22,386 INFO sqlalchemy.engine.Engine [generated in 0.00073s] ('dd27db58-3002-43d9-be59-675a95ab07bb', 'real_time_search', '', 10)
2024-07-18 11:39:22 | INFO | stdout | 2024-07-18 11:39:22,389 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:39:22 | INFO | stdout | [32mINFO[0m:     192.168.110.131:45842 - "[1mPOST /list_models HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:39:23 | INFO | controller | names: ['http://192.168.110.131:20002'], queue_lens: [0.0], ret: http://192.168.110.131:20002
2024-07-18 11:39:23 | INFO | stdout | [32mINFO[0m:     192.168.110.131:45848 - "[1mPOST /get_worker_address HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:39:23 | INFO | stdout | [32mINFO[0m:     192.168.110.131:60154 - "[1mPOST /worker_get_conv_template HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:39:23 | INFO | stdout | [32mINFO[0m:     192.168.110.131:60170 - "[1mPOST /model_details HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:39:23 | INFO | stdout | [32mINFO[0m:     192.168.110.131:60176 - "[1mPOST /count_token HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:39:23 | INFO | stdout | [32mINFO[0m:     192.168.110.131:39288 - "[1mPOST /v1/chat/completions HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:39:23 | INFO | stdout | [32mINFO[0m:     192.168.110.131:60188 - "[1mPOST /worker_generate_stream HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:39:26 | INFO | stdout | 2024-07-18 11:39:26,425 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:39:26 | INFO | stdout | 2024-07-18 11:39:26,428 INFO sqlalchemy.engine.Engine SELECT message.id, message.conversation_id, message.chat_type, message.query, message.response, message.meta_data, message.feedback_score, message.feedback_reason, message.create_time
2024-07-18 11:39:26 | INFO | stdout | FROM message
2024-07-18 11:39:26 | INFO | stdout | WHERE message.id = %s
2024-07-18 11:39:26 | INFO | stdout | 2024-07-18 11:39:26,429 INFO sqlalchemy.engine.Engine [generated in 0.00107s] ('86cfc90b-83c0-4eb9-9465-9dd3d33affc6',)
2024-07-18 11:39:26 | INFO | stdout | 2024-07-18 11:39:26,432 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:39:26 | INFO | stdout | 2024-07-18 11:39:26,434 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-18 11:39:26 | INFO | stdout | 2024-07-18 11:39:26,437 INFO sqlalchemy.engine.Engine UPDATE message SET response=%s WHERE message.id = %s
2024-07-18 11:39:26 | INFO | stdout | 2024-07-18 11:39:26,437 INFO sqlalchemy.engine.Engine [generated in 0.00063s] ('保罗·乔治加盟了洛杉矶快船队。', '86cfc90b-83c0-4eb9-9465-9dd3d33affc6')
2024-07-18 11:39:26 | INFO | stdout | 2024-07-18 11:39:26,439 INFO sqlalchemy.engine.Engine COMMIT
2024-07-18 11:39:35 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 11:39:35 | INFO | stdout | [32mINFO[0m:     192.168.110.131:54080 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:39:46 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 11:39:46 | INFO | stdout | [32mINFO[0m:     192.168.110.131:50346 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:40:20 | INFO | controller | Receive heart beat. http://192.168.110.131:21001
2024-07-18 11:40:20 | INFO | stdout | [32mINFO[0m:     192.168.110.131:55828 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:40:31 | INFO | controller | Receive heart beat. http://192.168.110.131:20002
2024-07-18 11:40:31 | INFO | stdout | [32mINFO[0m:     192.168.110.131:42602 - "[1mPOST /receive_heart_beat HTTP/1.1[0m" [32m200 OK[0m
2024-07-18 11:40:40 | WARNING | controller | Sending SIGKILL to {'zhipu-api': <Process name='api_worker - zhipu-api (1632018)' pid=1632018 parent=1631053 started daemon>}
2024-07-18 11:40:40 | WARNING | controller | Sending SIGKILL to {'chatglm3-6b': <Process name='model_worker - chatglm3-6b (1632017)' pid=1632017 parent=1631053 started daemon>}
2024-07-18 11:40:40 | WARNING | controller | Sending SIGKILL to <Process name='controller (1631760)' pid=1631760 parent=1631053 started daemon>
2024-07-18 11:40:40 | WARNING | controller | Sending SIGKILL to <Process name='openai_api (1632016)' pid=1632016 parent=1631053 started daemon>
2024-07-18 11:40:40 | WARNING | controller | Sending SIGKILL to <Process name='API Server (1632838)' pid=1632838 parent=1631053 started daemon>
2024-07-18 11:40:40 | INFO | controller | Process status: {'zhipu-api': <Process name='api_worker - zhipu-api (1632018)' pid=1632018 parent=1631053 started daemon>}
2024-07-18 11:40:40 | INFO | controller | Process status: {'chatglm3-6b': <Process name='model_worker - chatglm3-6b (1632017)' pid=1632017 parent=1631053 started daemon>}
2024-07-18 11:40:40 | INFO | controller | Process status: <Process name='controller (1631760)' pid=1631760 parent=1631053 started daemon>
2024-07-18 11:40:40 | INFO | controller | Process status: <Process name='openai_api (1632016)' pid=1632016 parent=1631053 started daemon>
2024-07-18 11:40:40 | INFO | controller | Process status: <Process name='API Server (1632838)' pid=1632838 parent=1631053 started daemon>
2024-07-18 11:40:40 | ERROR | stderr | Traceback (most recent call last):
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 584, in <module>
2024-07-18 11:40:40 | ERROR | stderr |     loop.run_until_complete(start_main_server())
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 495, in start_main_server
2024-07-18 11:40:40 | ERROR | stderr |     cmd = queue.get()
2024-07-18 11:40:40 | ERROR | stderr |   File "<string>", line 2, in get
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
2024-07-18 11:40:40 | ERROR | stderr |     kind, result = conn.recv()
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 255, in recv
2024-07-18 11:40:40 | ERROR | stderr |     buf = self._recv_bytes()
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
2024-07-18 11:40:40 | ERROR | stderr |     buf = self._recv(4)
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 384, in _recv
2024-07-18 11:40:40 | ERROR | stderr |     chunk = read(handle, remaining)
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 368, in f
2024-07-18 11:40:40 | ERROR | stderr |     raise KeyboardInterrupt(f"{signalname} received")
2024-07-18 11:40:40 | ERROR | stderr | KeyboardInterrupt: SIGINT received
2024-07-18 11:40:40 | ERROR | stderr | Exception ignored in atexit callback: <function _exit_function at 0x7f3359c09630>
2024-07-18 11:40:40 | ERROR | stderr | Traceback (most recent call last):
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/util.py", line 334, in _exit_function
2024-07-18 11:40:40 | ERROR | stderr |     _run_finalizers(0)
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
2024-07-18 11:40:40 | ERROR | stderr |     finalizer()
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/util.py", line 224, in __call__
2024-07-18 11:40:40 | ERROR | stderr |     res = self._callback(*self._args, **self._kwargs)
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/managers.py", line 674, in _finalize_manager
2024-07-18 11:40:40 | ERROR | stderr |     process.join(timeout=1.0)
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/process.py", line 149, in join
2024-07-18 11:40:40 | ERROR | stderr |     res = self._popen.wait(timeout)
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
2024-07-18 11:40:40 | ERROR | stderr |     if not wait([self.sentinel], timeout):
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/multiprocessing/connection.py", line 936, in wait
2024-07-18 11:40:40 | ERROR | stderr |     ready = selector.select(timeout)
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/util/anaconda3/envs/fufan_chat_api/lib/python3.10/selectors.py", line 416, in select
2024-07-18 11:40:40 | ERROR | stderr |     fd_event_list = self._selector.poll(timeout)
2024-07-18 11:40:40 | ERROR | stderr |   File "/home/00_rag/fufan-chat-api/startup.py", line 368, in f
2024-07-18 11:40:40 | ERROR | stderr |     raise KeyboardInterrupt(f"{signalname} received")
2024-07-18 11:40:40 | ERROR | stderr | KeyboardInterrupt: SIGINT received
